---
title: "QBS 103 Final Project V2"
author: "Elizabeth Chin"
date: "2023-08-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#set working directory
setwd("/Users/li_li/desktop/QBS_103_Final_Project/Data")

#read in csv files
gene.exp <- read.csv("QBS103_finalProject_geneExpression.csv", row.names = 1)

meta.data <- read.csv("QBS103_finalProject_metadata.csv", row.names = 1)
```


```{r}
#subset gene expression ABCA1, ABCA2, ABCA3
gene.ABCA123 <- gene.exp[c('ABCA1','ABCA2','ABCA3'),]

#transform rows to columns 
gene.ABCA123 <- as.data.frame(t(gene.ABCA123))
head(gene.ABCA123)
```

```{r}
#column bind two data frames
ABCA123.gene.exp.meta <- cbind(gene.ABCA123,meta.data)
head(ABCA123.gene.exp.meta, 1)
```

```{r}
#convert age to an integer
ABCA123.gene.exp.meta$age <- as.integer(ABCA123.gene.exp.meta$age) 
head(ABCA123.gene.exp.meta, 1)
```

```{r}
#create a new data frame to filter the unknown in sex
library(tidyverse)
clean_data <- ABCA123.gene.exp.meta %>% 
  filter(!grepl('unknown', sex)) 
```

```{r}
#create theme
newBlankTheme <- theme(# Remove all the extra borders and grid lines
        panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        # Define my axis
        axis.line = element_line(colour = "black", linewidth = rel(1)),
        # Set plot background
        plot.background = element_rect(fill = "white"),
        panel.background = element_blank(),
        legend.key = element_rect(fill = 'white'), 
        # Move legend
        legend.position = 'top')
```

```{r}
#define color palette
my_palette1 <- c("#A2CFFE") # Choose any colors you like
```


```{r}
#load the required package
library(ggplot2)
```

```{r}
#create italicize labels
#my_x1 <- expression(paste("Gene Expression ", italic("ABCA1")))
#my_title1 <- expression(paste("Frequency of People With Gene Expression ", italic("ABCA1")))
```

```{r}

#creating function to make histogram for gene expression

create_histogram <- function(df, gene){
  italic.gene <- c(gene)
  regular.lab <- c("Frequency of People With", "Gene Expression")
  my_title1 <- eval(bquote(expression(.(regular.lab[1]) ~.(regular.lab[2]) ~italic(.(italic.gene[1])))))
  my_x1 <- eval(bquote(expression(.(regular.lab[2]) ~italic(.(italic.gene[1])))))
  
  my_histogram <- ggplot(df, aes(x=.data[[gene]])) + 
  geom_histogram(binwidth = 2, fill = my_palette1, col="black") +
  stat_bin(binwidth=2, geom='text', color='white', aes(label=..count..),
           position=position_stack(vjust = 0.5)) +
  labs(x = my_x1,y = 'Frequency of People', title = my_title1) +
  theme(plot.title = element_text(hjust = 0.5)) +
  newBlankTheme 
  
  my_histogram
  
}

create_histogram(clean_data, "ABCA1")

```



```{r}
#define color palette
my_palette2 <- c("#D697C1") # Choose any colors you like
```


```{r}
#create italicize labels
#my_y2 <- expression(paste("Gene Expression ", italic("ABCA1")))
#my_title2 <- expression(paste("Gene Expression ", italic("ABCA1"), " By Age"))
```


```{r}
#creating function to make scatterplot for gene expression

create_scatterplot <- function(df, gene, cont.var){
  italic.gene <- c(gene)
  regular.lab <- c("Scatterplot of", "Gene Expression", "By Age")
  my_title2 <- eval(bquote(expression(.(regular.lab[1]) ~.(regular.lab[2]) ~italic(.(italic.gene[1])) ~.(regular.lab[3]))))
  my_y2 <- eval(bquote(expression(.(regular.lab[2]) ~italic(.(italic.gene[1])))))

  my_scatterplot <- ggplot(df,aes(x=.data[[cont.var]],y=.data[[gene]])) + 
  geom_point(color=my_palette2) + 
  labs(x = "Age", y = my_y2, title = my_title2) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  newBlankTheme
  
  my_scatterplot
  
}

create_scatterplot(clean_data, "ABCA1", cont.var = "age")


```


```{r}
#define color palette
my_palette3 <- c("#FFEEC4","#B1E3C7") # Choose any colors you like
```

```{r}
#create italicize labels
#my_y3 <- expression(paste("Gene Expression ", italic("ABCA1")))
#my_title3 <- expression(paste("Gene Expression ", italic("ABCA1"), " By Sex & ICU Status"))
```

```{r}
#creating function to make boxplot for gene expression

create_boxplot <- function(df, gene, x.cat, color.cat){
  italic.gene <- c(gene)
  regular.lab <- c("Boxplot of", "Gene Expression", "By Sex & ICU Status")
  my_title3 <- eval(bquote(expression(.(regular.lab[1]) ~.(regular.lab[2]) ~italic(.(italic.gene[1])) ~.(regular.lab[3]))))
  my_y3 <- eval(bquote(expression(. ~.(regular.lab[2]) ~italic(.(italic.gene[1])))))
  
  
  my_boxplot <- ggplot(df, aes(x=.data[[x.cat]], y=.data[[gene]], fill=.data[[color.cat]])) +
  theme(legend.title = element_blank()) +
  geom_boxplot() +
  scale_fill_manual(values = my_palette3, labels = c("Not Admitted to ICU", "Admitted to ICU")) +
  labs(x = "Sex",
       y = my_y3,
       fill = "ICU Status",
       title = my_title3) +
  theme(plot.title = element_text(hjust = 0.5)) +
  newBlankTheme
  
  my_boxplot
  
}

create_boxplot(clean_data, "ABCA1", x.cat = "sex", color.cat = "icu_status")

```


```{r}
#this function takes in the name of the df, list of one or more gene names, one continuous covariate, and a list of two categorical covariates
all_plots <- function(df, specific.g, cont.var1, cat.var2){
  h_plot <- create_histogram(df, specific.g)
  s_plot <- create_scatterplot(df, specific.g, cont.var1)
  b_plot <- create_boxplot(df, specific.g, x.cat = cat.var2[1], color.cat = cat.var2[2])
  
  plot_list <- list(h_plot, s_plot, b_plot)
  plot_list
}
```


```{r}
spec.cat <- c("sex", "icu_status")
spec.cont <- c("age")
spec.gene <- c("ABCA1", "ABCA2", "ABCA3")
```


```{r}
#implement a loop through all of the selected genes to generate my figures using the function I created above
for (i in 1:length(spec.gene)){
  plot_gene <- all_plots(clean_data, spec.gene[i], spec.cont, spec.cat)
  
  print(plot_gene)
}
```









